server:
  port: 8080

spring:
  application:
    name: GLITTER-APP

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/Glitter
    username: postgres
    password: pgAdmin
    driverClassName: org.postgresql.Driver  


#app: 
#  secret: codewithmayur 